### ISSUE TITLE
Cliff preset does not match A.N.T. Landscape

### ISSUE THREAD

**Issue by aarongerber** [nerk987/txa_ant#1]
I've checked all the settings I can see and I don't see a reason for it... but the cliff preset has the edges folded up and down creating a very not realistic view of a cliff. 

![image](https://user-images.githubusercontent.com/1500624/79049983-9c1f0b80-7bec-11ea-9f0e-a11fef872ae0.png)

**Comment by aarongerber** [comment]
This appears to be caused because the plugin chooses Mapping > Extension > Repeat, but it should be Extend or Clip. Would be nice to have a update to fix this, but I would classify this issue as S3 or Major priority since there is a work around. Thanks!

**Comment by nerk987** [comment]
Thanks for the report, and sorry for the delay. Version v2.81.5 should resolve this by making the 'Extend' mapping the default.
