### ISSUE TITLE
"Module not Found Error:  no module named txa ant" upon activating plugin

### ISSUE THREAD

**Issue by mitko2025** [nerk987/txa_ant#14]
![image](https://user-images.githubusercontent.com/56450059/195622739-7c51a465-0995-4c47-aed5-1255527feca5.png)

I get this error when activating the plugin. see settings below

![image](https://user-images.githubusercontent.com/56450059/195622861-42457c94-f0f6-44d7-8526-b1c600e59932.png)
![image](https://user-images.githubusercontent.com/56450059/195623097-bba4f1ae-3023-4316-8715-d69f0f4d92a8.png)

**Comment by nerk987** [comment]
It sounds like the common problem when the Github source zip file is downloaded instead of the addon zip file.

Make sure you download the file "txa_ant_3_00_4.zip from the link where it says:

Addon Download: txa_ant_3_00_4.zip
