### ISSUE TITLE
Cannot apply any textures in landscape eroder

### ISSUE THREAD

**Issue by Nancy-R** [nerk987/txa_ant#15]
When I choose a preferred Material in the Landscape Eroder and click the button I just get a white plane or nothing changes. Somehow I added a water texture on the water plane but I cannot make the terrain change from the normal default. 
![Screen Shot 2022-11-03 at 3 30 53 PM](https://user-images.githubusercontent.com/109319806/199820163-11613336-0836-496a-926c-1df4f7d23c92.png)
I am running blender 3.2.2 on n iMac M1

**Comment by nerk987** [comment]
Hi. Would you mind listing any errors that are occurring in the system console when you click on the "Landscape Eroder" button?

**Comment by Nancy-R** [comment]
Thank you so much for contacting me. I switched computers and it worked. I created a couple of nice landscapes and exported them . I want to use them in Unity but when I place my player marker on it is so minuscule even if I scale down the terrain. Any ideas? Or do I have to use a different process for Unity in txt. Sent from my iPhoneOn Nov 12, 2022, at 4:33 PM, nerk987 ***@***.***> wrote:﻿
Hi. Would you mind listing any errors that are occurring in the system console when you click on the "Landscape Eroder" button?

**Comment by nerk987** [comment]
Sorry, I don't have any experience with Unity.

**Comment by Nancy-R** [comment]
Basically Unity takes .fbx files so I assumed that exporting following your tutorials with the textures would suffice. I was finally able to load into Unity and had to scale down the landscape to get the player in but I can’t get it to load on my Oculus in Boneless after following all the steps (which I have doe many times) to create a level . So I guess this is out of both of our experiences. Thank you again for responding so quickly. I can at least get my students to learn how to use txa_ant.
