### ISSUE TITLE
Custom Heightmap for texture

### ISSUE THREAD

**Issue by Steveeboh** [nerk987/txa_ant#17]
Hello
I want to create a Custom Island.

I addet the TXA Landscape Add-on for that purpuse. with that I can easaly create random Islands but if I ad my own Heightmap the geometry of the Island is alright but all the other textures are adoptet from the initial Island created. Does anyone know how i can create all textures custom for my heightmap ?
<img width="933" alt="Bildschirmfoto 2024-03-21 um 15 10 37" src="https://github.com/nerk987/txa_ant/assets/150012950/6b03b254-1f2b-44a0-8ff1-79bfe199e8e5">

**Comment by nerk987** [comment]
You can use your own heightmap. Generate a landscape at the resolution of your heightmap. Switch from the 3D view to the image editor, select the 'ant01_heightmap' from the pulldown and delete it using the 'x'. From the 'Image' menu, load your own height map (preferably a 16 bit or deeper image). Change the name at the top to 'ant01_heightmap'. From the 'File\External Data' menu, choose 'Pack Resources'. Go the the 'TXA LAndscape' panel and choose 'Landscape Eroder'. You should get an eroded and textured model using your heightmap.

**Comment by Steveeboh** [comment]
Thank you very much. Its working now
