### ISSUE TITLE
Bake to PBR instant crash

### ISSUE THREAD

**Issue by DiademDev** [nerk987/txa_ant#18]
Identifier:            org.blenderfoundation.blender
Version:               4.0.2 (4.0.2 2023-12-05)
Code Type:             X86-64 (Native)
OS Version:            macOS 14.5 (23F79)

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [44819]
Model: iMac20,1, BootROM 2022.100.22.0.0 (iBridge: 21.16.5077.0.0,0), 6 processors, 6-Core Intel Core i5, 3.3 GHz, 40 GB, SMC 
Graphics: AMD Radeon Pro 5300, AMD Radeon Pro 5300, PCIe, 4 GB

**Comment by nerk987** [comment]
Thanks for the report.
Could I have a little more information? Does the crash happen every time you click on the "Bake to PBR" button?
Could you try the simplest case of:
1. Open blender 2. Add TXA Landscape 3. Press Bake to PBR
Could you try using Blender 4.1? 
I don't have access to a MAC, so there may be some issues I can't look into.

**Comment by DiademDev** [comment]
No worries. So far yes, it just crashes instantly after pressing the bake to PBR button. I have just tried the same thing on another Mac with same Blender version and same results. I will try with Blender 4.1 and get back to you.

**Comment by DiademDev** [comment]
Okay just tried on Blender 4.1 - it doesnt crash anymore. 
It does crash if there is no texture applied to the model if I follow your directions above (for obvious reasons). Might be a good idea to try and catch a nil object in that case, this might fix the issue for version 4.02... perhaps.
