### ISSUE TITLE
Preferred Material

### ISSUE THREAD

**Issue by Pat2E215** [nerk987/txa_ant#19]
When changing the Preferred Material nothing happens, it remains on ant01_NormalOnly.  Using Blender 4.1.  Tried with several presets

**Comment by Pat2E215** [comment]
Is there any way I can get this to work?  I've tried on 2 different PCs and the materials do not change.

**Comment by nerk987** [comment]
A little more information please...

1. You change the Preferred Material to, for example "Desert"
   - Does the preferred material just flip back to normal? Or stay on "Desert"
 2. Hit "Landscape Eroder".
   - Is the preferred material still desert? Is the material still "ant01_normal"? Did the landscape change to be more eroded? Were there errors?

The materials are just standard Blender materials in sub-directory "Materials" in the add-on directory. You could try appending one and changing the material manually. 

Do you have a special directory setup for add-ons to be installed to. Perhaps TXA_ant is having trouble with that.
