### ISSUE TITLE
Doesn't work with Blender 2.90

### ISSUE THREAD

**Issue by murphofwye** [nerk987/txa_ant#5]
Get an error like below everytime I try to activate it in preferences.

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\txa_ant-master\__init__.py", line 49, in <module>
    from txa_ant import add_mesh_ant_landscape
ModuleNotFoundError: No module named 'txa_ant'

**Comment by problems-2** [comment]
same i also got that issue did you manage to fix it?

**Comment by nerk987** [comment]
@problems-2  If you got the error above (That includes the 'txa_ant-master_init_.py' reference), then it looks like you didn't download the correct zip file. If you go to the main txa_ant github page where the instructions are shown and click on the 'txa_ant_3_00_2.zip' link in the instructions, then this should install ok in Blender 3.0 Alpha. If you're using Blender 2.9x, you should go to the releases and download 'txa_ant_2_91_1.zip'.

Although it should install on Blender version 3.0, there are problems when you run it with the latest alpha version. They have been changing the shader nodes which creates problems for the addon. I'll have another release of the addon up soon to fix these issues.
