### ISSUE TITLE
Can not run with ACES

### ISSUE THREAD

**Issue by hifishhe** [nerk987/txa_ant#7]
Can not run with ACES 1.2

**Comment by nerk987** [comment]
txa_ant creates the heightmaps with the colorspace 'Linear', and although ACES has many similar colorspaces, none are called 'Linear'. Both Blender and ACES have a 'raw' colorspace that would be suitable, but one has a capital 'R' and one doesn't and it's case sensitive. Go figure.

Perhaps it would be easiest for you to edit your ACES config.io file. Just find the 'raw' colorspace, copy it and change the name to 'Linear'.

Perhaps even copy all of Blender's colorspace definitions to the end of the ACES file, just in case there are other applications that rely on one or another of these to be present.
